name: Publish to npm on merge to master

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update package.json version
        run: node update-package-version.js

      - name: Install dependencies
        run: npm install

      - name: Build package (if necessary)
        run: npm run build

      - name: Compile package
        run: npm run compile

      - name: TEST fake NPM_AUTH_TOKEN
        run: echo ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Publish to npm
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
